<?php

return [
    'oracle' => [
        'driver'         => 'oracle',
        'tns'            => env('DB_ORCL_TNS', ''),
        'host'           => env('DB_ORCL_HOST', ''),
        'port'           => env('DB_ORCL_PORT', '1521'),
        'database'       => env('DB_ORCL_DATABASE', ''),
        'service_name'   => env('DB_ORCL_SERVICENAME', ''),
        'username'       => env('DB_ORCL_USERNAME', ''),
        'password'       => env('DB_ORCL_PASSWORD', ''),
        'charset'        => env('DB_ORCL_CHARSET', 'AL32UTF8'),
        'prefix'         => env('DB_ORCL_PREFIX', ''),
        'prefix_schema'  => env('DB_ORCL_SCHEMA_PREFIX', ''),
        'edition'        => env('DB_ORCL_EDITION', 'ora$base'),
        'server_version' => env('DB_ORCL_SERVER_VERSION', '11g'),
        'load_balance'   => env('DB_ORCL_LOAD_BALANCE', 'yes'),
        'max_name_len'   => env('DB_ORCL_MAX_NAME_LEN', 30),
        'dynamic'        => [],
        'sessionVars' => [
            'NLS_TIME_FORMAT' => 'HH24:MI:SS',
            'NLS_DATE_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_TZ_FORMAT' => 'YYYY-MM-DD HH24:MI:SS TZH:TZM',
            'NLS_NUMERIC_CHARACTERS' => '.,',
        ],
    ],
    'oraclecloud' => [
        'driver'         => 'oracle',
        'tns'            => env('DB_ORACLOUD_TNS', ''),
        'host'           => env('DB_ORACLOUD_HOST', ''),
        'port'           => env('DB_ORACLOUD_PORT', '1521'),
        'database'       => env('DB_ORACLOUD_DATABASE', ''),
        'service_name'   => env('DB_ORACLOUD_SERVICENAME', ''),
        'username'       => env('DB_ORACLOUD_USERNAME', ''),
        'password'       => env('DB_ORACLOUD_PASSWORD', ''),
        'charset'        => env('DB_ORACLOUD_CHARSET', 'AL32UTF8'),
        'prefix'         => env('DB_ORACLOUD_PREFIX', ''),
        'prefix_schema'  => env('DB_ORACLOUD_SCHEMA_PREFIX', ''),
        'edition'        => env('DB_ORACLOUD_EDITION', 'ora$base'),
        'server_version' => env('DB_ORACLOUD_SERVER_VERSION', '11g'),
        'load_balance'   => env('DB_ORACLOUD_LOAD_BALANCE', 'yes'),
        'max_name_len'   => env('DB_ORACLOUD_MAX_NAME_LEN', 30),
        'dynamic'        => [],
        'sessionVars' => [
            'NLS_TIME_FORMAT' => 'HH24:MI:SS',
            'NLS_DATE_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_TZ_FORMAT' => 'YYYY-MM-DD HH24:MI:SS TZH:TZM',
            'NLS_NUMERIC_CHARACTERS' => '.,',
        ],
    ],
];
